name: Windows-Build
on: 
  # push代码时触发workflow
  push:
    paths:
      - 'autosub/*'
      - 'patches/*'
      - 'pytranscriber/*'
      - 'main.py'
      - 'LICENSE'
      - '.github/workflows/windows-build.yml'
  pull_request:
    paths:
      - 'autosub/*'
      - 'patches/*'
      - 'pytranscriber/*'
      - 'main.py'
      - 'LICENSE'
      - '.github/workflows/windows-build.yml'
jobs:
  build:
    name: Build
    # 运行平台， windows-latest目前是windows server 2019 
    # 参考文档 https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md
    runs-on: windows-2019
    env:
      targetName: HelloActions-Qt.exe
    # 步骤
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install MinGW
        # You may pin to the exact commit or the version.
        # uses: egor-tensin/setup-mingw@f3c5d799aadf8fa230ac67a422b01dd085bbc96b
        uses: egor-tensin/setup-mingw@v2

      - name: Setup FFmpeg
        # You may pin to the exact commit or the version.
        # uses: FedericoCarboni/setup-ffmpeg@dbe266744738dd1fa54db0ecb35d11461c94a90a
        uses: FedericoCarboni/setup-ffmpeg@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip3 install pyQt5
          pip3 install autosub
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      
      # tag 查询github-Release
      # 上传artifacts          
      - uses: actions/upload-artifact@v2
        with:
          name: main.exe
          path: dist/main.exe
      # tag 上传Release
      - name: uploadRelease
        if: startsWith(github.event.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: test.zip
          asset_name: test.zip
          tag: ${{ github.ref }}
          overwrite: true 
